"use client";

import { useMemo, useState } from "react";

type Entry = {
  en: string;
  fr: string;
  beginner: string;
  professional: string;
  related: string[];
};

const entries: Entry[] = [
  { en: "Basis point", fr: "point de base", beginner: "A basis point is one hundredth of one percentage point. 25 bps = 0.25 percentage point.", professional: "A standardized unit for small changes in rates, yields, spreads and fees; 100 bps = 1 percentage point.", related: ["Yield", "Spread", "Interest rate"] },
  { en: "Yield", fr: "rendement", beginner: "Yield describes the return generated by an investment relative to its price or value, depending on the specific definition used.", professional: "A return measure whose exact construction depends on the instrument: current yield, yield to maturity, earnings yield and dividend yield are not interchangeable.", related: ["Bond", "YTM", "Coupon"] },
  { en: "Yield curve", fr: "courbe des taux", beginner: "A yield curve compares interest rates on similar bonds with different maturities.", professional: "The term structure of yields across maturities; slope and curvature embed policy expectations, term premium and macro risk.", related: ["2s10s", "Duration", "Rates"] },
  { en: "Credit spread", fr: "écart de crédit", beginner: "The extra yield investors demand to hold a risky bond instead of a safer benchmark.", professional: "The yield premium over a benchmark reflecting expected loss, liquidity, risk aversion, technicals and other non-rate components.", related: ["Credit risk", "High yield", "Default"] },
  { en: "Duration", fr: "duration", beginner: "A measure of how sensitive a bond price is to changes in interest rates.", professional: "A first-order measure of price sensitivity to yield changes; modified, effective and key-rate duration answer different risk questions.", related: ["Convexity", "Bond", "Yield"] },
  { en: "Liquidity", fr: "liquidité", beginner: "Liquidity describes how easily an asset can be bought or sold without moving its price too much.", professional: "The ability to transact size with limited price impact, tight spreads and reliable market depth under normal or stressed conditions.", related: ["Bid-ask spread", "Market depth", "Funding"] },
  { en: "Bid-ask spread", fr: "écart acheteur-vendeur", beginner: "The bid is what buyers offer; the ask is what sellers request. The difference is the spread.", professional: "The quoted transaction-cost wedge between best bid and best ask, influenced by liquidity, volatility, inventory risk and competition.", related: ["Liquidity", "Market making", "Order book"] },
  { en: "Volatility", fr: "volatilité", beginner: "Volatility describes how much and how quickly prices move.", professional: "A measure of return dispersion that can be historical, realized or implied; it is not the same thing as permanent loss risk.", related: ["VIX", "Options", "Risk"] },
  { en: "Implied volatility", fr: "volatilité implicite", beginner: "The level of future price movement implied by option prices.", professional: "The volatility input that reconciles an option-pricing model with the observed option premium, varying by strike and maturity.", related: ["Options", "Vega", "Volatility surface"] },
  { en: "Delta", fr: "delta", beginner: "Delta approximates how much an option price may change when the underlying asset moves by one unit.", professional: "The first derivative of option value with respect to the underlying price and a common hedge ratio for small spot moves.", related: ["Gamma", "Options", "Hedging"] },
  { en: "WACC", fr: "coût moyen pondéré du capital", beginner: "WACC combines the cost of debt and the cost of equity to estimate a company's overall financing cost.", professional: "The blended required return on operating capital, weighted by market-value capital structure and commonly used to discount unlevered FCF.", related: ["DCF", "Cost of equity", "Cost of debt"] },
  { en: "Free cash flow", fr: "flux de trésorerie disponible", beginner: "Cash a business generates after the spending needed to operate and invest in the business.", professional: "Cash flow available to capital providers after operating needs and reinvestment; FCFF and FCFE serve different valuation frameworks.", related: ["DCF", "FCFF", "FCFE"] },
];

export default function DictionaryExplorer() {
  const [query, setQuery] = useState("");
  const [professional, setProfessional] = useState(false);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return entries;
    return entries.filter((item) => [item.en, item.fr, ...item.related].join(" ").toLowerCase().includes(q));
  }, [query]);

  return (
    <div className="workspace-stack">
      <section className="dictionary-toolbar">
        <label>
          <span className="control-label">SEARCH ENGLISH OR FRENCH</span>
          <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: duration, rendement, WACC..." />
        </label>
        <div>
          <span className="control-label">DEFINITION MODE</span>
          <div className="chip-row">
            <button className={!professional ? "chip active" : "chip"} onClick={() => setProfessional(false)} type="button">Beginner</button>
            <button className={professional ? "chip active" : "chip"} onClick={() => setProfessional(true)} type="button">Professional</button>
          </div>
        </div>
      </section>

      <section className="dictionary-result-meta">
        <span className="mini-label">{filtered.length} TERMS SHOWN</span>
        <p>French entries keep the English market term beside them so the vocabulary transfers directly into interviews and financial news.</p>
      </section>

      <section className="dictionary-grid">
        {filtered.map((item) => (
          <article className="dictionary-card" key={item.en}>
            <span className="mini-label">{item.fr}</span>
            <h2>{item.en}</h2>
            <p>{professional ? item.professional : item.beginner}</p>
            <div className="related-row">{item.related.map((term) => <span key={term}>{term}</span>)}</div>
          </article>
        ))}
      </section>

      {filtered.length === 0 && <div className="empty-state"><strong>No matching term yet.</strong><p>The production dictionary will expand to thousands of finance concepts.</p></div>}
    </div>
  );
}
