"use client";

import { useMemo, useState } from "react";
import { useLanguage } from "@/components/language-provider";

type Entry = {
  en: string;
  fr: string;
  beginner: string;
  beginnerFr: string;
  professional: string;
  professionalFr: string;
  related: string[];
};

const entries: Entry[] = [
  { en: "Basis point", fr: "point de base", beginner: "A basis point is one hundredth of one percentage point. 25 bps = 0.25 percentage point.", beginnerFr: "Un point de base / basis point représente un centième de point de pourcentage. 25 bps = 0,25 point de pourcentage.", professional: "A standardized unit for small changes in rates, yields, spreads and fees; 100 bps = 1 percentage point.", professionalFr: "Unité standardisée pour mesurer de petites variations de taux / rates, rendements / yields, spreads et frais. 100 bps = 1 point de pourcentage.", related: ["Yield / rendement", "Spread / écart", "Interest rate / taux d’intérêt"] },
  { en: "Yield", fr: "rendement", beginner: "Yield describes the return generated by an investment relative to its price or value, depending on the specific definition used.", beginnerFr: "Le rendement / yield décrit le retour généré par un investissement par rapport à son prix ou sa valeur, selon la définition utilisée.", professional: "A return measure whose exact construction depends on the instrument: current yield, yield to maturity, earnings yield and dividend yield are not interchangeable.", professionalFr: "Mesure de rendement dont la construction dépend de l’instrument : rendement courant / current yield, rendement à maturité / yield to maturity, earnings yield et dividend yield ne sont pas interchangeables.", related: ["Bond / obligation", "YTM", "Coupon"] },
  { en: "Yield curve", fr: "courbe des taux", beginner: "A yield curve compares interest rates on similar bonds with different maturities.", beginnerFr: "Une courbe des taux / yield curve compare les rendements de titres similaires ayant des maturités / maturities différentes.", professional: "The term structure of yields across maturities; slope and curvature embed policy expectations, term premium and macro risk.", professionalFr: "Structure par terme / term structure des rendements selon les maturités. Sa pente / slope et sa courbure / curvature intègrent les anticipations de politique monétaire, la prime de terme / term premium et le risque macro.", related: ["2s10s", "Duration", "Rates / taux"] },
  { en: "Credit spread", fr: "écart de crédit", beginner: "The extra yield investors demand to hold a risky bond instead of a safer benchmark.", beginnerFr: "L’écart de crédit / credit spread est le rendement supplémentaire demandé pour détenir une obligation plus risquée plutôt qu’une référence plus sûre / benchmark.", professional: "The yield premium over a benchmark reflecting expected loss, liquidity, risk aversion, technicals and other non-rate components.", professionalFr: "Prime de rendement par rapport à un benchmark reflétant la perte attendue / expected loss, la liquidité / liquidity, l’aversion au risque, les facteurs techniques et d’autres composantes hors taux.", related: ["Credit risk / risque de crédit", "High yield", "Default / défaut"] },
  { en: "Duration", fr: "duration", beginner: "A measure of how sensitive a bond price is to changes in interest rates.", beginnerFr: "La duration mesure la sensibilité du prix d’une obligation / bond aux variations des taux d’intérêt / interest rates.", professional: "A first-order measure of price sensitivity to yield changes; modified, effective and key-rate duration answer different risk questions.", professionalFr: "Mesure de premier ordre de la sensibilité du prix aux variations de rendement / yield. Duration modifiée / modified duration, effective duration et key-rate duration répondent à des questions de risque différentes.", related: ["Convexity / convexité", "Bond / obligation", "Yield / rendement"] },
  { en: "Liquidity", fr: "liquidité", beginner: "Liquidity describes how easily an asset can be bought or sold without moving its price too much.", beginnerFr: "La liquidité / liquidity décrit la facilité avec laquelle un actif peut être acheté ou vendu sans trop faire bouger son prix.", professional: "The ability to transact size with limited price impact, tight spreads and reliable market depth under normal or stressed conditions.", professionalFr: "Capacité à traiter une taille importante / transact size avec un impact limité sur le prix, des spreads serrés et une profondeur de marché / market depth fiable en conditions normales ou stressées.", related: ["Bid-ask spread / écart acheteur-vendeur", "Market depth / profondeur de marché", "Funding / financement"] },
  { en: "Bid-ask spread", fr: "écart acheteur-vendeur", beginner: "The bid is what buyers offer; the ask is what sellers request. The difference is the spread.", beginnerFr: "Le bid est le prix proposé par les acheteurs, l’ask celui demandé par les vendeurs. La différence est le bid-ask spread / écart acheteur-vendeur.", professional: "The quoted transaction-cost wedge between best bid and best ask, influenced by liquidity, volatility, inventory risk and competition.", professionalFr: "Écart de coût de transaction coté entre le meilleur bid et le meilleur ask, influencé par la liquidité, la volatilité, le risque d’inventaire / inventory risk et la concurrence.", related: ["Liquidity / liquidité", "Market making", "Order book / carnet d’ordres"] },
  { en: "Volatility", fr: "volatilité", beginner: "Volatility describes how much and how quickly prices move.", beginnerFr: "La volatilité / volatility décrit l’ampleur et la vitesse des mouvements de prix.", professional: "A measure of return dispersion that can be historical, realized or implied; it is not the same thing as permanent loss risk.", professionalFr: "Mesure de dispersion des rendements pouvant être historique, réalisée / realized ou implicite / implied. Elle n’est pas équivalente au risque de perte permanente.", related: ["VIX", "Options", "Risk / risque"] },
  { en: "Implied volatility", fr: "volatilité implicite", beginner: "The level of future price movement implied by option prices.", beginnerFr: "La volatilité implicite / implied volatility correspond au niveau de mouvement futur du prix suggéré par le prix des options.", professional: "The volatility input that reconciles an option-pricing model with the observed option premium, varying by strike and maturity.", professionalFr: "Paramètre de volatilité qui permet à un modèle de valorisation d’options / option-pricing model de reproduire la prime observée, avec des niveaux différents selon le strike et la maturité.", related: ["Options", "Vega", "Volatility surface / surface de volatilité"] },
  { en: "Delta", fr: "delta", beginner: "Delta approximates how much an option price may change when the underlying asset moves by one unit.", beginnerFr: "Le delta approxime la variation du prix d’une option lorsque le sous-jacent / underlying asset varie d’une unité.", professional: "The first derivative of option value with respect to the underlying price and a common hedge ratio for small spot moves.", professionalFr: "Première dérivée de la valeur de l’option par rapport au prix du sous-jacent et ratio de couverture / hedge ratio courant pour de petits mouvements du spot.", related: ["Gamma", "Options", "Hedging / couverture"] },
  { en: "WACC", fr: "coût moyen pondéré du capital", beginner: "WACC combines the cost of debt and the cost of equity to estimate a company's overall financing cost.", beginnerFr: "Le WACC / coût moyen pondéré du capital combine le coût de la dette / cost of debt et le coût des capitaux propres / cost of equity pour estimer le coût global de financement d’une entreprise.", professional: "The blended required return on operating capital, weighted by market-value capital structure and commonly used to discount unlevered FCF.", professionalFr: "Rendement exigé combiné sur le capital opérationnel, pondéré selon la structure du capital en valeur de marché et couramment utilisé pour actualiser le FCF non endetté / unlevered FCF.", related: ["DCF", "Cost of equity / coût des capitaux propres", "Cost of debt / coût de la dette"] },
  { en: "Free cash flow", fr: "flux de trésorerie disponible", beginner: "Cash a business generates after the spending needed to operate and invest in the business.", beginnerFr: "Le flux de trésorerie disponible / free cash flow est la trésorerie générée après les dépenses nécessaires au fonctionnement et à l’investissement de l’entreprise.", professional: "Cash flow available to capital providers after operating needs and reinvestment; FCFF and FCFE serve different valuation frameworks.", professionalFr: "Flux disponible pour les apporteurs de capitaux après besoins opérationnels et réinvestissement. FCFF et FCFE correspondent à des cadres de valorisation / valuation différents.", related: ["DCF", "FCFF", "FCFE"] },
];

export default function DictionaryExplorer() {
  const { isFrench, text } = useLanguage();
  const [query, setQuery] = useState("");
  const [professional, setProfessional] = useState(false);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return entries;
    return entries.filter((item) => [item.en, item.fr, ...item.related].join(" ").toLowerCase().includes(q));
  }, [query]);

  return (
    <div className="workspace-stack">
      <section className="dictionary-toolbar">
        <label><span className="control-label">{text("SEARCH ENGLISH OR FRENCH", "RECHERCHER EN FRANÇAIS OU EN ANGLAIS")}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={text("Try: duration, yield, WACC...", "Essaie : duration, rendement, WACC…")} /></label>
        <div><span className="control-label">{text("DEFINITION MODE", "MODE DE DÉFINITION")}</span><div className="chip-row"><button className={!professional ? "chip active" : "chip"} onClick={() => setProfessional(false)} type="button">{text("Beginner", "Débutant")}</button><button className={professional ? "chip active" : "chip"} onClick={() => setProfessional(true)} type="button">{text("Professional", "Professionnel")}</button></div></div>
      </section>

      <section className="dictionary-result-meta">
        <span className="mini-label">{isFrench ? `${filtered.length} TERMES AFFICHÉS` : `${filtered.length} TERMS SHOWN`}</span>
        <p>{text("French entries keep the English market term beside them so the vocabulary transfers directly into interviews and financial news.", "En français, le terme anglais utilisé sur les marchés reste toujours à côté du terme français afin que le vocabulaire soit directement réutilisable en entretien et dans l’actualité financière.")}</p>
      </section>

      <section className="dictionary-grid">
        {filtered.map((item) => (
          <article className="dictionary-card" key={item.en}>
            <span className="mini-label">{isFrench ? item.en : item.fr}</span>
            <h2>{isFrench ? `${item.fr} / ${item.en}` : item.en}</h2>
            <p>{professional ? (isFrench ? item.professionalFr : item.professional) : (isFrench ? item.beginnerFr : item.beginner)}</p>
            <div className="related-row">{item.related.map((term) => <span key={term}>{term}</span>)}</div>
          </article>
        ))}
      </section>

      {filtered.length === 0 && <div className="empty-state"><strong>{text("No matching term yet.", "Aucun terme correspondant pour le moment.")}</strong><p>{text("The production dictionary will expand to thousands of finance concepts.", "Le dictionnaire final s’étendra à des milliers de concepts financiers.")}</p></div>}
    </div>
  );
}
